# Generated by Django 4.1 on 2022-08-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
    ]
