# Generated by Django 4.1 on 2022-08-28 10:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=main.models.user_directory_path),
        ),
    ]
