# Generated by Django 4.1 on 2022-10-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_cover_alter_book_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='book',
        ),
    ]
