# Generated by Django 4.1 on 2022-08-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='book',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, to='main.book'),
        ),
    ]
