# Generated by Django 4.1 on 2022-08-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(unique=True, upload_to='book_files/'),
        ),
    ]
