# Generated by Django 4.1 on 2022-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='book',
            field=models.ManyToManyField(to='main.book'),
        ),
    ]
