# Generated by Django 4.1 on 2022-08-23 15:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_book_cover_alter_book_author_remove_book_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=main.models.user_directory_path),
        ),
    ]
