# Generated by Django 4.1 on 2022-08-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_userprofile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcontent',
            old_name='user_owner',
            new_name='content_owner',
        ),
    ]
