# Generated by Django 4.1 on 2022-08-23 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_rename_user_owner_bookcontent_content_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontent',
            name='content_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
