# Generated by Django 4.1 on 2022-08-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_bookcontent_content_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcontent',
            old_name='content_owner',
            new_name='user',
        ),
    ]
