# Generated by Django 4.1 on 2022-08-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_content_owner_bookcontent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcontent',
            old_name='book_file',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bookcontent'),
        ),
    ]
