# Generated by Django 4.1 on 2022-08-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='introduce',
        ),
    ]
