# Generated by Django 4.1 on 2022-08-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_userprofile_age_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
